blacklist:
 - fuck
 - nigger
 - shit
 - tits
 - nigga
 - ass
 - horny
 - blowjob
 - queer
 - shitface
 - boner
 - hentai
 - erection
 - penis
 - cock
 - shaft
 - c0ck
 - fck
 - titties
 - bitch
 - anus
 - arse
 - vagina
 - pussy
 - boobs
 - arsehole
 - axwound